export const brandsAndModels = {
  Samsung: [
    "Galaxy S24 Ultra",
    "Galaxy Note 20",
    "Galaxy Z Flip",
    "Galaxy S21",
    "Galaxy A52",
    "Galaxy M31",
    "Galaxy A72",
    "Galaxy F41",
    "Galaxy Z Fold 3",
    "Galaxy M12",
    "Galaxy A32",
    "Galaxy A22",
    "Galaxy M21",
    "Galaxy A12",
    "Galaxy A03s",
    "Galaxy F22",
    "Galaxy A52s",
    "Galaxy M32",
    "Galaxy A71",
    "Galaxy A51",
    "Galaxy M51",
    "Galaxy S20",
    "Galaxy Note 10",
    "Galaxy S10",
    "Galaxy S9",
    "Galaxy Note 9",
    "Galaxy A80",
    "Galaxy A70",
    "Galaxy J8",
    "Galaxy J6",
  ],
  Apple: [
    "iPhone 16",
    "iPhone 16 Pro",
    "iPhone SE",
    "iPhone 15",
    "iPhone 15 Pro",
    "iPhone 14",
    "iPhone 14 Pro",
    "iPhone 13",
    "iPhone 13 Pro",
    "iPhone 12",
    "iPhone 12 Pro",
    "iPhone 11",
    "iPhone 11 Pro",
    "iPhone X",
    "iPhone XR",
    "iPhone XS",
    "iPhone 8",
    "iPhone 8 Plus",
    "iPhone 7",
    "iPhone 7 Plus",
    "iPhone 6S",
    "iPhone 6S Plus",
    "iPhone 6",
    "iPhone 6 Plus",
    "iPhone 5S",
    "iPhone 5C",
    "iPhone 5",
    "iPhone 4S",
    "iPhone 4",
  ],
  Xiaomi: [
    "Redmi Note 13 Pro",
    "Mi 11 Ultra",
    "Mi Mix Fold",
    "Redmi Note 12",
    "Mi 10",
    "Redmi Note 11",
    "Mi Note 10",
    "Redmi Note 9",
    "Mi 9",
    "Redmi Note 8",
    "Mi 8",
    "Redmi Note 7",
    "Mi 6",
    "Redmi Note 6",
    "Mi 5",
    "Redmi Note 5",
    "Mi 4",
    "Redmi Note 4",
    "Mi 3",
    "Redmi Note 3",
    "Mi 2",
    "Redmi Note 2",
    "Mi 1",
    "Redmi Note",
    "Mi A3",
    "Mi A2",
    "Mi A1",
    "Redmi K40",
    "Redmi K30",
  ],
  Vivo: [
    "Vivo X90",
    "Vivo Y72",
    "Vivo V21",
    "Vivo Y20",
    "Vivo Y50",
    "Vivo Y30",
    "Vivo Y12",
    "Vivo Y11",
    "Vivo V19",
    "Vivo V17",
    "Vivo V15",
    "Vivo V11",
    "Vivo V9",
    "Vivo V7",
    "Vivo V5",
    "Vivo V3",
    "Vivo V1",
    "Vivo Y95",
    "Vivo Y93",
    "Vivo Y91",
    "Vivo Y85",
    "Vivo Y83",
    "Vivo Y81",
    "Vivo Y71",
    "Vivo Y69",
    "Vivo Y66",
    "Vivo Y55",
    "Vivo Y53",
    "Vivo Y51",
  ],
  Oppo: [
    "Oppo Find X5",
    "Oppo Reno6",
    "Oppo A54",
    "Oppo A53",
    "Oppo A52",
    "Oppo A51",
    "Oppo A31",
    "Oppo A15",
    "Oppo A12",
    "Oppo A11",
    "Oppo A7",
    "Oppo A5",
    "Oppo A3",
    "Oppo A1",
    "Oppo R11",
    "Oppo R9",
    "Oppo R7",
    "Oppo R5",
    "Oppo R3",
    "Oppo R1",
    "Oppo F19",
    "Oppo F17",
    "Oppo F15",
    "Oppo F11",
    "Oppo F9",
    "Oppo F7",
    "Oppo F5",
    "Oppo F3",
    "Oppo F1",
  ],
  Realme: [
    "Realme GT 2",
    "Realme 8 Pro",
    "Realme C25",
    "Realme C21",
    "Realme 7i",
    "Realme 7 Pro",
    "Realme 6 Pro",
    "Realme 6i",
    "Realme 6",
    "Realme 5i",
    "Realme 5 Pro",
    "Realme 5",
    "Realme X3",
    "Realme X2 Pro",
    "Realme X2",
    "Realme X",
    "Realme U1",
    "Realme 3 Pro",
    "Realme 3",
    "Realme C1",
    "Realme 2 Pro",
    "Realme 2",
    "Realme 1",
    "Realme Narzo 30",
    "Realme Narzo 20",
    "Realme Narzo 10",
    "Realme Narzo 50",
    "Realme C25s",
    "Realme C20A",
  ],
  Motorola: [
    "Motorola Razr 2024",
    "Motorola Edge 20",
    "Moto G60",
    "Moto G50",
    "Moto G40",
    "Moto G30",
    "Moto G10",
    "Moto G9",
    "Moto G8",
    "Moto G7",
    "Moto G6",
    "Moto G5",
    "Moto G4",
    "Moto G3",
    "Moto G2",
    "Moto G",
    "Moto E7",
    "Moto E6",
    "Moto E5",
    "Moto E4",
    "Moto E3",
    "Moto E2",
    "Moto E",
    "Moto X4",
    "Moto X3",
    "Moto X2",
    "Moto X",
    "Moto Z4",
    "Moto Z3",
  ],
  Huawei: [
    "Huawei P50 Pro",
    "Huawei Mate 40",
    "Huawei Nova 9",
    "Huawei P40",
    "Huawei Mate 30",
    "Huawei P30",
    "Huawei Nova 8",
    "Huawei Nova 7",
    "Huawei Y9",
    "Huawei Y8",
    "Huawei Y7",
    "Huawei Y6",
    "Huawei Y5",
    "Huawei Y4",
    "Huawei Y3",
    "Huawei Y2",
    "Huawei Y1",
    "Huawei Mate X2",
    "Huawei Mate Xs",
    "Huawei Mate X",
    "Huawei Enjoy 20",
    "Huawei Enjoy 10",
    "Huawei Enjoy 9",
    "Huawei Enjoy 8",
    "Huawei Enjoy 7",
    "Huawei Enjoy 6",
    "Huawei Enjoy 5",
    "Huawei Enjoy 4",
    "Huawei Enjoy 3",
  ],
  OnePlus: [
    "OnePlus 9",
    "OnePlus 8",
    "OnePlus 7T",
    "OnePlus 7",
    "OnePlus 6T",
    "OnePlus 6",
    "OnePlus 5T",
    "OnePlus 5",
    "OnePlus 3T",
    "OnePlus 3",
    "OnePlus 2",
    "OnePlus One",
    "OnePlus Nord 2",
    "OnePlus Nord",
    "OnePlus Nord CE",
    "OnePlus Nord N200",
    "OnePlus Nord N100",
    "OnePlus 8T",
    "OnePlus 8 Pro",
    "OnePlus 7 Pro",
    "OnePlus 7T Pro",
    "OnePlus 6T McLaren",
    "OnePlus 6 Avengers",
    "OnePlus 5T Star Wars",
    "OnePlus 3T Colette",
    "OnePlus 2 Sandstone",
    "OnePlus One Bamboo",
    "OnePlus Nord LE",
    "OnePlus 8 Cyberpunk",
    "OnePlus 7T Cyberpunk",
  ],
  Sony: [
    "Xperia 1 III",
    "Xperia 5 III",
    "Xperia 10 III",
    "Xperia 1 II",
    "Xperia 5 II",
    "Xperia 10 II",
    "Xperia 1",
    "Xperia 5",
    "Xperia 10",
    "Xperia XZ3",
    "Xperia XZ2",
    "Xperia XZ1",
    "Xperia XZ",
    "Xperia XA2",
    "Xperia XA1",
    "Xperia X",
    "Xperia Z5",
    "Xperia Z4",
    "Xperia Z3",
    "Xperia Z2",
    "Xperia Z1",
    "Xperia Z",
    "Xperia SP",
    "Xperia T",
    "Xperia S",
    "Xperia P",
    "Xperia U",
    "Xperia X10",
    "Xperia X8",
    "Xperia E5",
  ],
};
